version: "3.9"

services:
  hello-app:
    build: .
    ports:
      - "3001:3001"
    networks:
      - rust-node-net
    deploy:
      resources:
        limits:
          memory: 300M

networks:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  rust-node-net:
    driver: bridge